---
title: "Ians drug trial analysis"
output:
  revealjs::revealjs_presentation:
    theme: night
    highlight: espresso
    center: true
---

```{r setup, include=FALSE}
library(tidyverse)
library(stringr)
library(forcats)
library(knitr)
library(kableExtra)
library(visdat)

knitr::opts_chunk$set(echo = TRUE, comment = "")

show_df <- function(df){
  modify_if(df, .p = is_character, ~ replace(.x, is.na(.x), "")) %>%
  kable(striped = TRUE, format = "markdown") %>% 
  print()
}
```

## Import data and checksum

Should be...
425ec869e2a885d2da60d6bb16902555

```{r}
FILE <- "../data/ians-drug-trial_biochemistry-results_20171020.xls"
tools::md5sum(FILE)
dat <- readxl::read_excel(FILE, sheet = 1)
```
  
  
```{r, results='asis', echo=FALSE}
dat %>% show_df()
```
## Fill down the missing columns

```{r}
dat <- dat %>% 
  fill(sex, age, treatment)
```
```{r, results='asis', echo=FALSE}
dat %>% show_df()
```
## Make the subject ID nice

```{r}
dat <- dat %>% 
  mutate(subject = paste0("A", str_pad(subject, 3, "left", "0")))
```

```{r, results='asis', echo=FALSE}
dat %>% show_df()
```
## Clean the sex/status column

```{r}
kable(dat %>% group_by(sex) %>% tally())

dat <- dat %>%
  mutate(sex = case_when(sex == "female nneutered" ~ "fn",
                         sex == "male entire" ~ "me",
                         sex == "MN" ~ "mn",
                         TRUE ~ sex))
```

```{r, results='asis', echo=FALSE}
dat %>% show_df()
```

## Separate sex/status into 2 columns

```{r}
dat <- dat %>% 
  tidyr::separate(sex, c("sex", "neuter_status"), c(1))
```

```{r, results='asis', echo=FALSE}
dat %>% show_df()
```

## Make ages in months into years

```{r}
dat <- dat %>%
  mutate(age = case_when(grepl("month", age) ~ parse_number(age) / 12,
                         TRUE ~ parse_number(age)))
```

```{r, results='asis', echo=FALSE}
dat %>% show_df()
```
## Gather results and create week column

```{r}
dat <- dat %>%
  tidyr::gather("week", "value", `week 1`:`week 4`) %>% 
  mutate(week = str_extract(week, "\\d"))
```

```{r, results='asis', echo=FALSE}
dat %>% show_df()
```

## Check result values for obvious typos and correct

```{r, fig.height=3}
ggplot(dat, aes(x = value)) +
  geom_histogram(binwidth = 5) +
  coord_cartesian(ylim = c(0, 10)) + 
  labs(title = "Quick histogram of all values",
       subtitel = "NB: y axis truncated")
```

---

```{r}
dat %>% 
  dplyr::filter(value > 50) %>% 
  dplyr::select(subject, week, rep, value)
```
---

```{r}

dat <- dat %>%
  mutate(value = case_when(subject == "A006" &
                             week == 1 &
                             rep == 2 ~ 6.04,
                           
                           subject == "A012" &
                             week == 2 &
                             rep == 2 ~ 7.76,
                           
                           subject == "A012" &
                             week == 3 &
                             rep == 1 ~ 7.27,
                           
                           subject == "A003" &
                             week == 4 &
                             rep == 2 ~ 4.08,
                           
                           subject == "A004" &
                             week == 4 &
                             rep == 1 ~ 7.37,
                           
                           TRUE ~ value))
  
```
---

```{r, results='asis', echo=FALSE}
dat %>% show_df()
```

## Save tidied and cleaned data

```{r}
# write_csv(dat, "output/ians-drug-trial_biochemistry-result_tidy_20171020.csv")
```

