---
title: Ian's Drug Trial - tidy
author: Ian Handel
date: 2017
output:
  revealjs::revealjs_presentation:
    transition: fade
    highlight: zenburn
    theme: simple
---


```{r setup, include=FALSE}
library(tidyverse)
library(stringr)
library(forcats)
library(knitr)
library(kableExtra) # striping

knitr::opts_chunk$set(echo = TRUE, comment = "")

show_df <- function(df){
  modify_if(df, .p = is_character, ~ replace(.x, is.na(.x), "")) %>%
  kable(format = "markdown") %>% 
  print()
}
```

## Import data and checksum

```{r}
DATA_FILE_NAME <- "../data/ih-trial_results_20171020.xlsx"
tools::md5sum(DATA_FILE_NAME)
dat <- readxl::read_excel(DATA_FILE_NAME, sheet = 1)
```
  

```{r, results='asis', echo=FALSE}
dat %>% show_df()
```

---
## Fill down the missing columns

```{r}
dat <- dat %>% 
  fill(sex, age, treatment)
```
```{r, results='asis', echo=FALSE}
dat %>% show_df()
```

---

## Make the subject ID nice

```{r}
dat <- dat %>% 
  mutate(subject = paste0("A", str_pad(subject, 3, "left", "0")))
```

```{r, results='asis', echo=FALSE}
dat %>% show_df()
```

---
## Clean the sex/status column

```{r}
dat %>%
  group_by(sex) %>%
  tally() %>% 
  kable(format = "html")
```

---

```{r}
dat <- dat %>%
  mutate(sex = case_when(sex == "female nneutered" ~ "fn",
                         sex == "male entire" ~ "me",
                         sex == "MN" ~ "mn",
                         TRUE ~ sex))
```

```{r, results='asis', echo=FALSE}
dat %>% show_df()
```

---
## Separate sex/status into 2 columns

```{r}
dat <- dat %>% 
  tidyr::separate(sex, c("sex", "neuter_status"), 1)
```

```{r, results='asis', echo=FALSE}
dat %>% show_df()
```

---
## Make ages in months into years

```{r, size=0.1}
dat <- dat %>%
  mutate(age = case_when(
                    str_detect(age, "month") ~ parse_number(age) / 12,
                    TRUE ~ parse_number(age)))
```

```{r, results='asis', echo=FALSE}
dat %>% show_df()
```

---
## Gather results and create week column

```{r}
dat <- dat %>%
  tidyr::gather("week", "value", `week 1`:`week 4`) %>% 
  mutate(week = parse_number(week))
```

```{r, results='asis', echo=FALSE}
dat %>% show_df()
```

---
## Check result values for obvious typos

```{r, fig.height=3}
ggplot(dat, aes(x = value)) +
  geom_histogram(binwidth = 5) +
  coord_cartesian(ylim = c(0, 10)) + 
  labs(title = "Quick histogram of all values",
       subtitle = "NB: y axis truncated")
```

---

```{r}
dat %>% 
  dplyr::filter(value > 50) %>% 
  dplyr::select(subject, week, rep, value) %>% 
  kable(format = "html")
```
---

```{r}

dat <- dat %>%
  mutate(value = case_when(subject == "A006" &
                             week == 1 &
                             rep == 2 ~         6.04,
                           
                           subject == "A012" &
                             week == 2 &
                             rep == 2 ~         7.76,
                           
                           subject == "A012" &
                             week == 3 &
                             rep == 1 ~         7.23,
                           
                           subject == "A003" &
                             week == 4 &
                             rep == 2 ~         4.08,
                           
                           subject == "A004" &
                             week == 4 &
                             rep == 1 ~         7.37,
                           
                           TRUE ~               value))
  
```
---

```{r, results='asis', echo=FALSE}
dat %>% show_df()
```


---

## Save tidied and cleaned data
```{r}
write_csv(dat, "../data/ih-trial_results_20171020_tidy.csv")
```

