---
title: "Excel to R Translation"
author: "JRDM"
date: "19 October 2017"
output: 
  html_document:
    toc: true 
    toc_float: true
    toc_depth: 3
---


So with the dataset *Dragon Survey*....

###Sheet: Very Raw Data
**Variables**

Variable Name         |Variable Type
----------------------|--------------------------
Dragon                |Nominal
Gender                |3 Level Categorical
Home Range            |3 Level Categorical
Dragon Age            | Continuous
Wingspan              | Continuous
N Princesses Captured | Continuous
Answer to Question... |Free Text
Gold Affinity Score   |6 Level Ordinal Variable

We want to ...

1. Assign each case a unique ID
    + Excel skill = fill down
2. Remove names from the active worksheet
    + Excel skill = delete column (or many other ways you could do this. Could include data management here - I have a 'raw' file where append the unique ID and then save it somewhere else separate from my 'working data')
3. Find out how many levels are in each category
    + Excel skill = filtering (a clear win for R)
4. Create an 'exclude' variable
    + Excel skill = insert column
5. Code "Gold Affinity Score"
    + Excel skill = Can be done with a sort - you'll hate me for this, I write nested IF functions if I have to do this in Excel
6. Summarise the free text response into a categorical response (Eat/Ransom/Rescue)
    + Excel skill = ability to see data and edit it quickly
      ++ Eat - princess gets eaten
      ++ Ransom - dragon sells them or says ransom
      ++ Rescue - dragon lets the princess be rescued
7. Check for outliers - 3 outliers in Wingspan
    + Excel skill = filtering (again an easy win for R)
  
###Sheet: Data Stage 2
We want to ...

1. Visualise relationships between dragon age, wingspan, home range, gender, princesses captured, gold affinity socre and princess outcomes.
    + Excel skills = charts 
  
###Sheet: Large Home Ranges
We want to ...

1. Create a subset of data 
    + Excel skill = copy/paste and filtering 
2. See multiple tables in one sheet
    + Excel skill = pivot tables



### Other Things To Include...
* Melting and casting/throwing data in R is so much easier than in Excel! 
* skimr!
* anything else . . . .

